version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: npm run dev
    ports:
      - '8000:3001'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/infraestructure/database/create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - app-network # Garantir que esteja na mesma rede

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
